apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: game-sessions-table
  namespace: kro
spec:
  schema:
    apiVersion: v1alpha1
    kind: GameSessionsTable
    spec:
      # Table configuration
      tableName: string | default="game2048-sessions-dev"
      region: string | default="eu-west-1"
      billingMode: string | default="PAY_PER_REQUEST"

  resources:
    # DynamoDB Table for game sessions using ACK DynamoDB Controller
    - id: gameSessionsTable
      template:
        apiVersion: dynamodb.services.k8s.aws/v1alpha1
        kind: Table
        metadata:
          name: ${schema.spec.tableName}
          namespace: ${schema.metadata.namespace}
          labels:
            app.kubernetes.io/name: ${schema.spec.tableName}
            app.kubernetes.io/managed-by: kro
        spec:
          tableName: ${schema.spec.tableName}
          keySchema:
            - attributeName: id
              keyType: HASH
          attributeDefinitions:
            - attributeName: id
              attributeType: "S"
          billingMode: ${schema.spec.billingMode}
          tags:
            - key: Project
              value: game2048
            - key: ManagedBy
              value: KRO
            - key: Region
              value: ${schema.spec.region}
            - key: Purpose
              value: game-sessions