apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: s3-backup-bucket
  namespace: kro
spec:
  schema:
    apiVersion: v1alpha1
    kind: S3BackupBucket
    spec:
      # Bucket configuration
      bucketName: string | required=true
      region: string | default="eu-west-1"
      versioning: boolean | default=true
      encryption: boolean | default=true
      blockPublicAccess: boolean | default=true

    status:
      bucketArn: string
      bucketDomainName: string

  resources:
    # S3 Bucket using ACK S3 Controller
    - id: s3Bucket
      template:
        apiVersion: s3.services.k8s.aws/v1alpha1
        kind: Bucket
        metadata:
          name: ${schema.spec.bucketName}
          namespace: ${schema.metadata.namespace}
          labels:
            app.kubernetes.io/name: ${schema.spec.bucketName}
            app.kubernetes.io/managed-by: kro
        spec:
          name: ${schema.spec.bucketName}
          tagging:
            tagSet:
              - key: Project
                value: game2048
              - key: Purpose
                value: leaderboard-backup
              - key: ManagedBy
                value: KRO
              - key: Region
                value: ${schema.spec.region}
