apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: game-2048
  labels:
    app: 2048-backend
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-backend
      component: backend
  template:
    metadata:
      labels:
        app: 2048-backend
        component: backend
    spec:
      containers:
      - name: backend
        image: 2048-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: PORT
          value: "8000"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
      restartPolicy: Always