apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: game-2048
  labels:
    app: 2048-frontend
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: 2048-frontend
      component: frontend
  template:
    metadata:
      labels:
        app: 2048-frontend
        component: frontend
    spec:
      containers:
      - name: frontend
        image: 2048-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "32Mi"
            cpu: "25m"
          limits:
            memory: "64Mi"
            cpu: "50m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 2
      restartPolicy: Always